### ISSUE TITLE
Feature Request: CSV Project Upload Functionality

### ISSUE THREAD

**Issue by coldicedcoffee** [wncc/Hello-FOSS-SOC-Portal#1]
We would like to implement a feature that allows users to upload project data from a CSV file. The CSV will contain multiple project entries, and the data should be processed and stored in the backend database.

Try to solve the issue here so that we can run it as a custom function : https://github.com/wncc/Hello-FOSS-SOC-Portal/blob/main/socbackend/projects/management/commands/upload_projects.py

**Comment by Adityaupadhye** [comment]
please review PR 17
- #17

**Comment by vaibhav1724** [comment]
kindly review PR #18
