### ISSUE TITLE
issue with missing files in the accounts tab

### ISSUE THREAD

**Issue by coldicedcoffee** [wncc/Hello-FOSS-SOC-Portal#22]
There are some files missing in the accounts app in socbackend, which are causing some unwanted errors in our code. We would like you to fix this so that atleast the website is up and running. This is a very simple issue and will only mostly test your basic GitHub and very  basic Django skills.

**Comment by Rushikeshmagdum0379** [comment]
Will You Assign This To Me @coldicedcoffee
