### ISSUE TITLE
Bug: Images Not Rendering on Frontend

### ISSUE THREAD

**Issue by coldicedcoffee** [wncc/Hello-FOSS-SOC-Portal#9]
Images in the project are not rendering or appearing on the frontend. This could be caused by incorrect file paths, missing image files, or issues with the image rendering component.

Steps to Reproduce:
Visit the page where the image is expected to appear.
Inspect the image tag using the browser's Developer Tools (Inspect > Network tab).
Check if the image file is missing or if the source path is incorrect.

**Comment by vaibhav1724** [comment]
Kindly check PR #18 
some images won't appear as the image name is incorrect in the CSV file itself hence it is unable to match the image in img folder
